name: Build Resume PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Puppeteer
      run: |
        npm install puppeteer
        
    - name: Convert HTML to PDF
      run: |
        node -e "
        const puppeteer = require('puppeteer');
        (async () => {
          const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          const page = await browser.newPage();
          await page.goto('file://${{ github.workspace }}/resume.html', {
            waitUntil: 'networkidle0'
          });
          await page.pdf({
            path: 'resume.pdf',
            format: 'A4',
            printBackground: true,
            margin: {
              top: '0.5in',
              right: '0.75in',
              bottom: '0.5in',
              left: '0.75in'
            }
          });
          await browser.close();
        })();
        "
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume.pdf
        
    - name: Commit PDF back to repo (optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.pdf
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update resume PDF"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}